# Generated by Django 4.2.16 on 2026-05-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Millilitres'), ('pcs', 'Pieces')], max_length=3)),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slice_count', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CakeBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_version_snapshot', models.JSONField(help_text='Snapshot of recipe + ingredients at time of baking')),
                ('quantity_baked', models.PositiveIntegerField(help_text='Number of whole cakes baked in this batch')),
                ('baked_by', models.CharField(max_length=100)),
                ('baked_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.recipe')),
            ],
            options={
                'verbose_name_plural': 'cake batches',
                'ordering': ['-baked_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='inventory.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
